//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsStore2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public int id { get; set; }

        [Display(Name = "Parent Item")]
        public string item_parent { get; set; }
        [Required]

        [Display(Name = "Brand")]
        public string item_brand { get; set; }
        [Required]
        [Display(Name = "Product Name")]

        public string item_name { get; set; }
        [Required]
        [Display(Name = "Product Category")]
        public string item_category { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Price")]
        public decimal item_price { get; set; }
        [Display(Name = "Stock")]
        public Nullable<int> item_stock { get; set; }

        [Display(Name = "Image Link")]
        public string item_img { get; set; }
        [AllowHtml]
        [Display(Name = "Product Description (HTML)")]
        public string item_shortdesc { get; set; }

/*        public bool isChecked { get; set; }
*/    }
}
